import type { CefrLevel } from '@/lib/types';

/**
 * Gunluk kelime havuzu: seviye basina 30 kelime.
 * Her gun 10 kelime deterministik olarak secilir (bkz. lib/vocabulary.ts).
 * Havuzu genisletmek icin bu dosyaya ayni bicimde kelime ekleyin.
 */
export interface VocabWord {
  /** Ingilizce kelime ya da kalip */
  word: string;
  /** Tur: isim, fiil, sifat, zarf, ifade ... */
  type: string;
  /** Turkce anlami */
  tr: string;
  /** Ingilizce ornek cumle */
  en: string;
  /** Ornek cumlenin Turkcesi */
  trExample: string;
  /** Istege bagli kullanim ipucu */
  tip?: string;
}

export const VOCABULARY: Record<CefrLevel, VocabWord[]> = {
  PreA1: [
    { word: 'hello', type: 'ifade', tr: 'merhaba', en: 'Hello! My name is Ali.', trExample: 'Merhaba! Benim adım Ali.' },
    { word: 'water', type: 'isim', tr: 'su', en: 'Can I have some water, please?', trExample: 'Biraz su alabilir miyim, lütfen?' },
    { word: 'apple', type: 'isim', tr: 'elma', en: 'I eat an apple every morning.', trExample: 'Her sabah bir elma yerim.' },
    { word: 'book', type: 'isim', tr: 'kitap', en: 'This book is very good.', trExample: 'Bu kitap çok güzel.' },
    { word: 'house', type: 'isim', tr: 'ev', en: 'My house is small but nice.', trExample: 'Evim küçük ama güzel.' },
    { word: 'cat', type: 'isim', tr: 'kedi', en: 'The cat is sleeping on the sofa.', trExample: 'Kedi koltukta uyuyor.' },
    { word: 'dog', type: 'isim', tr: 'köpek', en: 'My dog likes to play.', trExample: 'Köpeğim oynamayı sever.' },
    { word: 'eat', type: 'fiil', tr: 'yemek yemek', en: 'We eat dinner at seven.', trExample: 'Akşam yemeğini yedide yeriz.' },
    { word: 'drink', type: 'fiil', tr: 'içmek', en: 'I drink tea in the morning.', trExample: 'Sabahları çay içerim.' },
    { word: 'go', type: 'fiil', tr: 'gitmek', en: 'I go to school by bus.', trExample: 'Okula otobüsle giderim.' },
    { word: 'come', type: 'fiil', tr: 'gelmek', en: 'Please come here.', trExample: 'Lütfen buraya gel.' },
    { word: 'big', type: 'sıfat', tr: 'büyük', en: 'They live in a big city.', trExample: 'Büyük bir şehirde yaşıyorlar.' },
    { word: 'small', type: 'sıfat', tr: 'küçük', en: 'She has a small bag.', trExample: 'Küçük bir çantası var.' },
    { word: 'red', type: 'sıfat', tr: 'kırmızı', en: 'I like your red car.', trExample: 'Kırmızı arabanı beğendim.' },
    { word: 'family', type: 'isim', tr: 'aile', en: 'My family is very important to me.', trExample: 'Ailem benim için çok önemli.' },
    { word: 'friend', type: 'isim', tr: 'arkadaş', en: 'Ayşe is my best friend.', trExample: 'Ayşe benim en iyi arkadaşım.' },
    { word: 'school', type: 'isim', tr: 'okul', en: 'The school opens at eight.', trExample: 'Okul sekizde açılır.' },
    { word: 'teacher', type: 'isim', tr: 'öğretmen', en: 'Our teacher is very kind.', trExample: 'Öğretmenimiz çok nazik.' },
    { word: 'day', type: 'isim', tr: 'gün', en: 'Have a nice day!', trExample: 'İyi günler!' },
    { word: 'night', type: 'isim', tr: 'gece', en: 'Good night, see you tomorrow.', trExample: 'İyi geceler, yarın görüşürüz.' },
    { word: 'today', type: 'zarf', tr: 'bugün', en: 'Today is Monday.', trExample: 'Bugün pazartesi.' },
    { word: 'yes', type: 'ifade', tr: 'evet', en: 'Yes, I like coffee.', trExample: 'Evet, kahveyi severim.' },
    { word: 'no', type: 'ifade', tr: 'hayır', en: 'No, thank you.', trExample: 'Hayır, teşekkür ederim.' },
    { word: 'please', type: 'ifade', tr: 'lütfen', en: 'Please open the window.', trExample: 'Lütfen pencereyi aç.' },
    { word: 'thank you', type: 'ifade', tr: 'teşekkür ederim', en: 'Thank you for your help.', trExample: 'Yardımın için teşekkür ederim.' },
    { word: 'morning', type: 'isim', tr: 'sabah', en: 'I get up early in the morning.', trExample: 'Sabah erken kalkarım.' },
    { word: 'food', type: 'isim', tr: 'yiyecek', en: 'Turkish food is delicious.', trExample: 'Türk yemekleri lezzetlidir.' },
    { word: 'happy', type: 'sıfat', tr: 'mutlu', en: 'I am very happy today.', trExample: 'Bugün çok mutluyum.' },
    { word: 'name', type: 'isim', tr: 'isim', en: 'What is your name?', trExample: 'Adın ne?' },
    { word: 'love', type: 'fiil', tr: 'sevmek', en: 'I love my family.', trExample: 'Ailemi seviyorum.' },
  ],
  A1: [
    { word: 'always', type: 'zarf', tr: 'her zaman', en: 'I always brush my teeth before bed.', trExample: 'Yatmadan önce her zaman dişlerimi fırçalarım.', tip: 'Sıklık zarfları özneden sonra gelir: I always..., She always...' },
    { word: 'usually', type: 'zarf', tr: 'genellikle', en: 'We usually have lunch at noon.', trExample: 'Genellikle öğlen yemek yeriz.' },
    { word: 'weather', type: 'isim', tr: 'hava durumu', en: 'The weather is sunny today.', trExample: 'Bugün hava güneşli.' },
    { word: 'cheap', type: 'sıfat', tr: 'ucuz', en: 'This market is cheap and good.', trExample: 'Bu market ucuz ve iyi.' },
    { word: 'expensive', type: 'sıfat', tr: 'pahalı', en: 'The hotel was too expensive for us.', trExample: 'Otel bizim için fazla pahalıydı.' },
    { word: 'breakfast', type: 'isim', tr: 'kahvaltı', en: 'I have breakfast at eight o’clock.', trExample: 'Kahvaltıyı saat sekizde yaparım.', tip: '"have breakfast" kalıbında artikel kullanılmaz: a breakfast denmez.' },
    { word: 'work', type: 'fiil', tr: 'çalışmak', en: 'She works in a hospital.', trExample: 'O bir hastanede çalışıyor.' },
    { word: 'live', type: 'fiil', tr: 'yaşamak, oturmak', en: 'They live near the sea.', trExample: 'Denizin yakınında oturuyorlar.' },
    { word: 'buy', type: 'fiil', tr: 'satın almak', en: 'I want to buy a new phone.', trExample: 'Yeni bir telefon almak istiyorum.' },
    { word: 'open', type: 'fiil', tr: 'açmak', en: 'Can you open the door, please?', trExample: 'Kapıyı açar mısın, lütfen?' },
    { word: 'close', type: 'fiil', tr: 'kapatmak', en: 'The shop closes at nine.', trExample: 'Dükkân dokuzda kapanır.' },
    { word: 'listen', type: 'fiil', tr: 'dinlemek', en: 'I listen to music on the bus.', trExample: 'Otobüste müzik dinlerim.', tip: '"listen" fiilinden sonra "to" gelir: listen to music.' },
    { word: 'speak', type: 'fiil', tr: 'konuşmak', en: 'Do you speak English?', trExample: 'İngilizce konuşuyor musun?' },
    { word: 'understand', type: 'fiil', tr: 'anlamak', en: 'Sorry, I don’t understand.', trExample: 'Üzgünüm, anlamıyorum.' },
    { word: 'hungry', type: 'sıfat', tr: 'aç', en: 'I’m hungry. Let’s eat something.', trExample: 'Açım. Hadi bir şeyler yiyelim.' },
    { word: 'thirsty', type: 'sıfat', tr: 'susamış', en: 'The children are thirsty after the game.', trExample: 'Çocuklar oyundan sonra susadı.' },
    { word: 'tired', type: 'sıfat', tr: 'yorgun', en: 'He is tired because he worked a lot.', trExample: 'Çok çalıştığı için yorgun.' },
    { word: 'early', type: 'zarf', tr: 'erken', en: 'The train leaves early in the morning.', trExample: 'Tren sabah erken kalkıyor.' },
    { word: 'late', type: 'zarf', tr: 'geç', en: 'Don’t be late for the lesson.', trExample: 'Derse geç kalma.' },
    { word: 'near', type: 'edat', tr: 'yakın', en: 'There is a park near my house.', trExample: 'Evimin yakınında bir park var.' },
    { word: 'holiday', type: 'isim', tr: 'tatil', en: 'We are going on holiday in July.', trExample: 'Temmuzda tatile gidiyoruz.', tip: '"on holiday" kalıbını unutma: go on holiday, be on holiday.' },
    { word: 'ticket', type: 'isim', tr: 'bilet', en: 'How much is a bus ticket?', trExample: 'Otobüs bileti ne kadar?' },
    { word: 'money', type: 'isim', tr: 'para', en: 'I don’t have enough money.', trExample: 'Yeterli param yok.', tip: '"money" sayılamayan isimdir: monies değil, much money.' },
    { word: 'shop', type: 'isim', tr: 'dükkân, mağaza', en: 'The shop is next to the bank.', trExample: 'Dükkân bankanın yanında.' },
    { word: 'street', type: 'isim', tr: 'sokak, cadde', en: 'Our street is very quiet at night.', trExample: 'Sokağımız geceleri çok sessiz.' },
    { word: 'question', type: 'isim', tr: 'soru', en: 'Can I ask a question?', trExample: 'Bir soru sorabilir miyim?', tip: '"ask a question" birlikte kullanılır; make/do a question denmez.' },
    { word: 'answer', type: 'isim', tr: 'cevap', en: 'The answer is on page ten.', trExample: 'Cevap onuncu sayfada.' },
    { word: 'week', type: 'isim', tr: 'hafta', en: 'I play football twice a week.', trExample: 'Haftada iki kez futbol oynarım.' },
    { word: 'weekend', type: 'isim', tr: 'hafta sonu', en: 'What do you do at the weekend?', trExample: 'Hafta sonu ne yaparsın?' },
    { word: 'beautiful', type: 'sıfat', tr: 'güzel', en: 'İstanbul is a beautiful city.', trExample: 'İstanbul güzel bir şehir.' },
  ],
  A2: [
    { word: 'journey', type: 'isim', tr: 'yolculuk', en: 'The journey to Ankara takes five hours.', trExample: 'Ankara yolculuğu beş saat sürüyor.', tip: '"journey" yolculuğun kendisi, "trip" ise gidip gelme anlamındadır.' },
    { word: 'arrive', type: 'fiil', tr: 'varmak', en: 'We arrived at the airport at six.', trExample: 'Havalimanına altıda vardık.', tip: 'arrive at (bina/nokta), arrive in (şehir/ülke).' },
    { word: 'borrow', type: 'fiil', tr: 'ödünç almak', en: 'Can I borrow your pen?', trExample: 'Kalemini ödünç alabilir miyim?', tip: 'borrow = ödünç almak, lend = ödünç vermek. Karıştırma!' },
    { word: 'lend', type: 'fiil', tr: 'ödünç vermek', en: 'She lent me her umbrella.', trExample: 'Bana şemsiyesini ödünç verdi.' },
    { word: 'crowded', type: 'sıfat', tr: 'kalabalık', en: 'The metro is very crowded in the morning.', trExample: 'Metro sabahları çok kalabalık.' },
    { word: 'quiet', type: 'sıfat', tr: 'sessiz, sakin', en: 'I need a quiet place to study.', trExample: 'Ders çalışmak için sessiz bir yere ihtiyacım var.' },
    { word: 'decide', type: 'fiil', tr: 'karar vermek', en: 'We decided to stay at home.', trExample: 'Evde kalmaya karar verdik.', tip: 'decide + to + fiil: decide to go, decide to buy.' },
    { word: 'forget', type: 'fiil', tr: 'unutmak', en: 'Don’t forget to lock the door.', trExample: 'Kapıyı kilitlemeyi unutma.' },
    { word: 'remember', type: 'fiil', tr: 'hatırlamak', en: 'I can’t remember his name.', trExample: 'Onun adını hatırlayamıyorum.' },
    { word: 'invite', type: 'fiil', tr: 'davet etmek', en: 'They invited us to their wedding.', trExample: 'Bizi düğünlerine davet ettiler.' },
    { word: 'healthy', type: 'sıfat', tr: 'sağlıklı', en: 'Eating vegetables is healthy.', trExample: 'Sebze yemek sağlıklıdır.' },
    { word: 'dangerous', type: 'sıfat', tr: 'tehlikeli', en: 'Driving fast is dangerous.', trExample: 'Hızlı araba kullanmak tehlikelidir.' },
    { word: 'famous', type: 'sıfat', tr: 'ünlü', en: 'This city is famous for its castle.', trExample: 'Bu şehir kalesiyle ünlüdür.', tip: '"famous for" kalıbı: ünlü olunan şeyden önce "for" gelir.' },
    { word: 'weather forecast', type: 'isim', tr: 'hava tahmini', en: 'The weather forecast says it will rain.', trExample: 'Hava tahmini yağmur yağacağını söylüyor.' },
    { word: 'luggage', type: 'isim', tr: 'bagaj, valizler', en: 'Our luggage was too heavy.', trExample: 'Bagajımız çok ağırdı.', tip: 'Sayılamayan isim: a luggage denmez, a piece of luggage denir.' },
    { word: 'abroad', type: 'zarf', tr: 'yurt dışında', en: 'My sister studies abroad.', trExample: 'Kız kardeşim yurt dışında okuyor.', tip: '"to abroad" denmez: go abroad, live abroad.' },
    { word: 'improve', type: 'fiil', tr: 'geliştirmek', en: 'I want to improve my English.', trExample: 'İngilizcemi geliştirmek istiyorum.' },
    { word: 'practise', type: 'fiil', tr: 'pratik yapmak', en: 'You should practise speaking every day.', trExample: 'Her gün konuşma pratiği yapmalısın.', tip: 'practise + -ing: practise speaking, practise writing.' },
    { word: 'noisy', type: 'sıfat', tr: 'gürültülü', en: 'The neighbours are very noisy at night.', trExample: 'Komşular geceleri çok gürültülü.' },
    { word: 'comfortable', type: 'sıfat', tr: 'rahat', en: 'These shoes are really comfortable.', trExample: 'Bu ayakkabılar gerçekten rahat.' },
    { word: 'appointment', type: 'isim', tr: 'randevu', en: 'I have a doctor’s appointment at three.', trExample: 'Üçte doktor randevum var.', tip: 'make an appointment = randevu almak.' },
    { word: 'miss', type: 'fiil', tr: 'kaçırmak; özlemek', en: 'Hurry up or we will miss the bus.', trExample: 'Acele et yoksa otobüsü kaçıracağız.', tip: 'İki anlam: miss the bus (kaçırmak), miss you (özlemek).' },
    { word: 'return', type: 'fiil', tr: 'geri dönmek', en: 'He returned home very late.', trExample: 'Eve çok geç döndü.' },
    { word: 'stay', type: 'fiil', tr: 'kalmak', en: 'We stayed at a small hotel.', trExample: 'Küçük bir otelde kaldık.' },
    { word: 'weekend trip', type: 'isim', tr: 'hafta sonu gezisi', en: 'They planned a weekend trip to Bursa.', trExample: 'Bursa’ya bir hafta sonu gezisi planladılar.' },
    { word: 'delicious', type: 'sıfat', tr: 'lezzetli', en: 'The soup was absolutely delicious.', trExample: 'Çorba gerçekten lezzetliydi.' },
    { word: 'terrible', type: 'sıfat', tr: 'berbat', en: 'The traffic was terrible this morning.', trExample: 'Bu sabah trafik berbattı.' },
    { word: 'exciting', type: 'sıfat', tr: 'heyecan verici', en: 'The match was really exciting.', trExample: 'Maç gerçekten heyecan vericiydi.', tip: '-ing/-ed farkı: exciting (heyecan veren şey), excited (heyecanlanan kişi).' },
    { word: 'prefer', type: 'fiil', tr: 'tercih etmek', en: 'I prefer tea to coffee.', trExample: 'Çayı kahveye tercih ederim.', tip: 'prefer X to Y kalıbı: "than" değil "to" kullanılır.' },
    { word: 'enough', type: 'zarf', tr: 'yeterince', en: 'The water isn’t warm enough.', trExample: 'Su yeterince sıcak değil.', tip: 'enough sıfattan SONRA gelir: warm enough, good enough.' },
  ],
  B1: [
    { word: 'achieve', type: 'fiil', tr: 'başarmak, elde etmek', en: 'She achieved her goal of running a marathon.', trExample: 'Maraton koşma hedefini başardı.', tip: 'achieve a goal / success / a dream kalıplarıyla kullanılır.' },
    { word: 'avoid', type: 'fiil', tr: 'kaçınmak', en: 'You should avoid eating fast food.', trExample: 'Fast food yemekten kaçınmalısın.', tip: 'avoid + -ing: avoid eating, avoid making.' },
    { word: 'apply', type: 'fiil', tr: 'başvurmak', en: 'I applied for a summer job.', trExample: 'Bir yaz işine başvurdum.', tip: 'apply for (iş/pozisyon), apply to (kurum).' },
    { word: 'experience', type: 'isim', tr: 'deneyim', en: 'Do you have any experience in teaching?', trExample: 'Öğretmenlik deneyimin var mı?' },
    { word: 'opportunity', type: 'isim', tr: 'fırsat', en: 'This course is a great opportunity to learn.', trExample: 'Bu kurs öğrenmek için harika bir fırsat.', tip: 'opportunity to + fiil: opportunity to learn, to travel.' },
    { word: 'confident', type: 'sıfat', tr: 'kendinden emin', en: 'She feels confident about the exam.', trExample: 'Sınav konusunda kendine güveniyor.' },
    { word: 'disappointed', type: 'sıfat', tr: 'hayal kırıklığına uğramış', en: 'I was disappointed with the film.', trExample: 'Filmden hayal kırıklığına uğradım.' },
    { word: 'environment', type: 'isim', tr: 'çevre', en: 'Plastic bags harm the environment.', trExample: 'Plastik poşetler çevreye zarar verir.' },
    { word: 'pollution', type: 'isim', tr: 'kirlilik', en: 'Air pollution is a big problem in big cities.', trExample: 'Hava kirliliği büyük şehirlerde büyük bir sorundur.' },
    { word: 'increase', type: 'fiil', tr: 'artmak, artırmak', en: 'Prices increased by ten percent last year.', trExample: 'Fiyatlar geçen yıl yüzde on arttı.' },
    { word: 'decrease', type: 'fiil', tr: 'azalmak, azaltmak', en: 'The number of students decreased this term.', trExample: 'Öğrenci sayısı bu dönem azaldı.' },
    { word: 'suggest', type: 'fiil', tr: 'önermek', en: 'He suggested going to the cinema.', trExample: 'Sinemaya gitmeyi önerdi.', tip: 'suggest + -ing veya suggest that: "suggest to go" YANLIŞTIR.' },
    { word: 'complain', type: 'fiil', tr: 'şikâyet etmek', en: 'They complained about the slow service.', trExample: 'Yavaş servisten şikâyet ettiler.', tip: 'complain about something / to somebody.' },
    { word: 'employee', type: 'isim', tr: 'çalışan', en: 'The company has two hundred employees.', trExample: 'Şirketin iki yüz çalışanı var.', tip: 'employee = çalışan, employer = işveren.' },
    { word: 'salary', type: 'isim', tr: 'maaş', en: 'The job offers a good salary.', trExample: 'İş iyi bir maaş sunuyor.' },
    { word: 'skill', type: 'isim', tr: 'beceri', en: 'Communication skills are important at work.', trExample: 'İletişim becerileri işte önemlidir.' },
    { word: 'responsible', type: 'sıfat', tr: 'sorumlu', en: 'She is responsible for the new project.', trExample: 'Yeni projeden o sorumlu.', tip: 'responsible for + isim/-ing.' },
    { word: 'according to', type: 'edat', tr: '-e göre', en: 'According to the news, it will snow tomorrow.', trExample: 'Haberlere göre yarın kar yağacak.', tip: '"According to me" denmez; kendi görüşün için "in my opinion" kullan.' },
    { word: 'although', type: 'bağlaç', tr: '-e rağmen', en: 'Although it was raining, we went out.', trExample: 'Yağmur yağmasına rağmen dışarı çıktık.', tip: 'although + cümle; despite + isim.' },
    { word: 'however', type: 'zarf', tr: 'ancak, bununla birlikte', en: 'The hotel was nice. However, it was far from the beach.', trExample: 'Otel güzeldi. Ancak plaja uzaktı.' },
    { word: 'convenient', type: 'sıfat', tr: 'uygun, elverişli', en: 'Online shopping is very convenient.', trExample: 'İnternetten alışveriş çok pratik.' },
    { word: 'reliable', type: 'sıfat', tr: 'güvenilir', en: 'He is a reliable friend; he always helps.', trExample: 'O güvenilir bir arkadaş; her zaman yardım eder.' },
    { word: 'notice', type: 'fiil', tr: 'fark etmek', en: 'I noticed a mistake in the report.', trExample: 'Raporda bir hata fark ettim.' },
    { word: 'organise', type: 'fiil', tr: 'düzenlemek, organize etmek', en: 'We are organising a surprise party.', trExample: 'Sürpriz bir parti düzenliyoruz.' },
    { word: 'take part in', type: 'ifade', tr: 'katılmak', en: 'Fifty runners took part in the race.', trExample: 'Yarışa elli koşucu katıldı.', tip: 'take part in = participate in.' },
    { word: 'give up', type: 'ifade', tr: 'bırakmak, vazgeçmek', en: 'He gave up smoking two years ago.', trExample: 'İki yıl önce sigarayı bıraktı.', tip: 'give up + -ing: give up smoking.' },
    { word: 'look forward to', type: 'ifade', tr: 'dört gözle beklemek', en: 'I’m looking forward to seeing you.', trExample: 'Seni görmeyi dört gözle bekliyorum.', tip: 'to’dan sonra -ing gelir: look forward to seeing.' },
    { word: 'in advance', type: 'ifade', tr: 'önceden', en: 'Please book your tickets in advance.', trExample: 'Lütfen biletlerinizi önceden ayırtın.' },
    { word: 'immediately', type: 'zarf', tr: 'derhal, hemen', en: 'Call the doctor immediately.', trExample: 'Hemen doktoru ara.' },
    { word: 'necessary', type: 'sıfat', tr: 'gerekli', en: 'Is it necessary to bring a passport?', trExample: 'Pasaport getirmek gerekli mi?' },
  ],
  B2: [
    { word: 'accomplish', type: 'fiil', tr: 'başarmak, tamamlamak', en: 'We accomplished the task ahead of schedule.', trExample: 'Görevi planlanandan önce tamamladık.' },
    { word: 'assess', type: 'fiil', tr: 'değerlendirmek', en: 'Teachers assess students’ progress regularly.', trExample: 'Öğretmenler öğrencilerin gelişimini düzenli olarak değerlendirir.' },
    { word: 'crucial', type: 'sıfat', tr: 'çok önemli, kritik', en: 'Sleep plays a crucial role in learning.', trExample: 'Uyku, öğrenmede kritik bir rol oynar.', tip: 'play a crucial role in kalıbı sık kullanılır.' },
    { word: 'significant', type: 'sıfat', tr: 'önemli, kayda değer', en: 'There was a significant improvement in her grades.', trExample: 'Notlarında kayda değer bir gelişme oldu.' },
    { word: 'considerably', type: 'zarf', tr: 'önemli ölçüde', en: 'Prices vary considerably between cities.', trExample: 'Fiyatlar şehirler arasında önemli ölçüde değişir.' },
    { word: 'evidence', type: 'isim', tr: 'kanıt', en: 'There is strong evidence that exercise helps memory.', trExample: 'Egzersizin hafızaya yardımcı olduğuna dair güçlü kanıtlar var.', tip: 'Sayılamayan isim: an evidence denmez, a piece of evidence.' },
    { word: 'tendency', type: 'isim', tr: 'eğilim', en: 'He has a tendency to leave things until the last minute.', trExample: 'İşleri son dakikaya bırakma eğilimi var.' },
    { word: 'reluctant', type: 'sıfat', tr: 'isteksiz', en: 'She was reluctant to accept the offer.', trExample: 'Teklifi kabul etmekte isteksizdi.', tip: 'reluctant to + fiil.' },
    { word: 'thorough', type: 'sıfat', tr: 'kapsamlı, titiz', en: 'The police made a thorough search of the building.', trExample: 'Polis binada kapsamlı bir arama yaptı.' },
    { word: 'cope with', type: 'ifade', tr: 'başa çıkmak', en: 'It can be hard to cope with stress at work.', trExample: 'İşte stresle başa çıkmak zor olabilir.' },
    { word: 'carry out', type: 'ifade', tr: 'yürütmek, gerçekleştirmek', en: 'The scientists carried out a series of experiments.', trExample: 'Bilim insanları bir dizi deney gerçekleştirdi.', tip: 'carry out research/an experiment/a survey.' },
    { word: 'point out', type: 'ifade', tr: 'belirtmek, dikkat çekmek', en: 'She pointed out several errors in the plan.', trExample: 'Plandaki birkaç hataya dikkat çekti.' },
    { word: 'turn out', type: 'ifade', tr: 'ortaya çıkmak, sonuçlanmak', en: 'The rumour turned out to be false.', trExample: 'Söylentinin asılsız olduğu ortaya çıktı.', tip: 'turn out to be + sıfat/isim.' },
    { word: 'inevitable', type: 'sıfat', tr: 'kaçınılmaz', en: 'Some delay is inevitable in big projects.', trExample: 'Büyük projelerde bir miktar gecikme kaçınılmazdır.' },
    { word: 'controversial', type: 'sıfat', tr: 'tartışmalı', en: 'The new law is highly controversial.', trExample: 'Yeni yasa oldukça tartışmalı.' },
    { word: 'considering', type: 'edat', tr: 'göz önüne alındığında', en: 'Considering his age, he is very fit.', trExample: 'Yaşı göz önüne alındığında çok formda.' },
    { word: 'meanwhile', type: 'zarf', tr: 'bu arada', en: 'The pasta is cooking; meanwhile, prepare the sauce.', trExample: 'Makarna pişiyor; bu arada sosu hazırla.' },
    { word: 'consequence', type: 'isim', tr: 'sonuç', en: 'Skipping classes has serious consequences.', trExample: 'Dersleri asmanın ciddi sonuçları vardır.', tip: 'as a consequence = sonuç olarak.' },
    { word: 'contribute to', type: 'ifade', tr: 'katkıda bulunmak', en: 'Regular reading contributes to vocabulary growth.', trExample: 'Düzenli okuma kelime dağarcığının gelişmesine katkıda bulunur.' },
    { word: 'demanding', type: 'sıfat', tr: 'zorlu, talepkâr', en: 'Medicine is a demanding profession.', trExample: 'Tıp zorlu bir meslektir.' },
    { word: 'efficient', type: 'sıfat', tr: 'verimli', en: 'We need a more efficient way to store data.', trExample: 'Veriyi depolamak için daha verimli bir yola ihtiyacımız var.', tip: 'efficient = az kaynakla çok iş; effective = etkili, işe yarayan.' },
    { word: 'estimate', type: 'fiil', tr: 'tahmin etmek', en: 'Experts estimate that the repairs will cost millions.', trExample: 'Uzmanlar onarımların milyonlara mal olacağını tahmin ediyor.' },
    { word: 'gradually', type: 'zarf', tr: 'yavaş yavaş, giderek', en: 'Her English gradually improved over the year.', trExample: 'İngilizcesi yıl boyunca giderek gelişti.' },
    { word: 'in terms of', type: 'ifade', tr: 'açısından', en: 'In terms of price, this laptop is the best option.', trExample: 'Fiyat açısından bu dizüstü en iyi seçenek.' },
    { word: 'keep up with', type: 'ifade', tr: 'ayak uydurmak', en: 'It’s hard to keep up with new technology.', trExample: 'Yeni teknolojiye ayak uydurmak zor.' },
    { word: 'reliable source', type: 'isim', tr: 'güvenilir kaynak', en: 'Always check the news against a reliable source.', trExample: 'Haberleri her zaman güvenilir bir kaynaktan doğrula.' },
    { word: 'setback', type: 'isim', tr: 'aksilik, gerileme', en: 'The injury was a major setback for the team.', trExample: 'Sakatlık takım için büyük bir aksilikti.' },
    { word: 'overcome', type: 'fiil', tr: 'üstesinden gelmek', en: 'She overcame her fear of public speaking.', trExample: 'Topluluk önünde konuşma korkusunun üstesinden geldi.' },
    { word: 'prospect', type: 'isim', tr: 'olasılık, beklenti', en: 'The prospect of moving abroad excites him.', trExample: 'Yurt dışına taşınma ihtimali onu heyecanlandırıyor.' },
    { word: 'ultimately', type: 'zarf', tr: 'nihayetinde', en: 'Ultimately, the decision is yours.', trExample: 'Nihayetinde karar senin.' },
  ],
  C1: [
    { word: 'compelling', type: 'sıfat', tr: 'ikna edici, sürükleyici', en: 'She made a compelling argument for reform.', trExample: 'Reform için ikna edici bir savunma yaptı.', tip: 'compelling argument/evidence/reason sık kullanılan eşdizimlerdir.' },
    { word: 'nuance', type: 'isim', tr: 'ince ayrım, nüans', en: 'Translators must capture every nuance of meaning.', trExample: 'Çevirmenler anlamın her nüansını yakalamalıdır.' },
    { word: 'scrutinise', type: 'fiil', tr: 'ince ince incelemek', en: 'The committee scrutinised the budget line by line.', trExample: 'Komite bütçeyi satır satır inceledi.' },
    { word: 'undermine', type: 'fiil', tr: 'baltalamak, zayıflatmak', en: 'Constant criticism undermines confidence.', trExample: 'Sürekli eleştiri özgüveni zayıflatır.' },
    { word: 'alleviate', type: 'fiil', tr: 'hafifletmek', en: 'The new road should alleviate traffic congestion.', trExample: 'Yeni yol trafik sıkışıklığını hafifletmeli.' },
    { word: 'ambiguous', type: 'sıfat', tr: 'belirsiz, çok anlamlı', en: 'The contract wording is dangerously ambiguous.', trExample: 'Sözleşmenin ifadesi tehlikeli biçimde belirsiz.' },
    { word: 'deteriorate', type: 'fiil', tr: 'kötüleşmek', en: 'Relations between the two sides deteriorated rapidly.', trExample: 'İki taraf arasındaki ilişkiler hızla kötüleşti.' },
    { word: 'feasible', type: 'sıfat', tr: 'uygulanabilir', en: 'The plan is ambitious but feasible.', trExample: 'Plan iddialı ama uygulanabilir.' },
    { word: 'implication', type: 'isim', tr: 'dolaylı sonuç, ima', en: 'The ruling has implications for future cases.', trExample: 'Karar, gelecekteki davalar için dolaylı sonuçlar taşıyor.' },
    { word: 'meticulous', type: 'sıfat', tr: 'titiz', en: 'He kept meticulous records of every payment.', trExample: 'Her ödemenin titiz kaydını tuttu.' },
    { word: 'notwithstanding', type: 'edat', tr: '-e rağmen (resmî)', en: 'Notwithstanding the risks, they proceeded.', trExample: 'Risklere rağmen devam ettiler.', tip: 'Resmî/akademik dilde despite yerine kullanılabilir.' },
    { word: 'plausible', type: 'sıfat', tr: 'akla yatkın', en: 'Her explanation sounded plausible enough.', trExample: 'Açıklaması yeterince akla yatkın görünüyordu.' },
    { word: 'profound', type: 'sıfat', tr: 'derin, köklü', en: 'The internet has had a profound effect on society.', trExample: 'İnternetin toplum üzerinde derin bir etkisi oldu.' },
    { word: 'scarce', type: 'sıfat', tr: 'kıt, az bulunur', en: 'Clean water is scarce in the region.', trExample: 'Bölgede temiz su kıt.' },
    { word: 'substantiate', type: 'fiil', tr: 'kanıtlarla desteklemek', en: 'He could not substantiate his claims.', trExample: 'İddialarını kanıtlayamadı.' },
    { word: 'trade-off', type: 'isim', tr: 'ödünleşim, denge', en: 'There is a trade-off between speed and accuracy.', trExample: 'Hız ile doğruluk arasında bir ödünleşim vardır.' },
    { word: 'akin to', type: 'ifade', tr: 'benzer, yakın', en: 'Learning a language is akin to building a muscle.', trExample: 'Dil öğrenmek kas geliştirmeye benzer.' },
    { word: 'at stake', type: 'ifade', tr: 'tehlikede, söz konusu', en: 'Thousands of jobs are at stake in this decision.', trExample: 'Bu kararda binlerce iş tehlikede.' },
    { word: 'by and large', type: 'ifade', tr: 'genel olarak', en: 'By and large, the reforms have been successful.', trExample: 'Genel olarak reformlar başarılı oldu.' },
    { word: 'delve into', type: 'ifade', tr: 'derinlemesine incelemek', en: 'The book delves into the causes of the crisis.', trExample: 'Kitap krizin nedenlerini derinlemesine inceliyor.' },
    { word: 'discrepancy', type: 'isim', tr: 'tutarsızlık, fark', en: 'Auditors found discrepancies in the accounts.', trExample: 'Denetçiler hesaplarda tutarsızlıklar buldu.' },
    { word: 'elaborate on', type: 'ifade', tr: 'ayrıntılandırmak', en: 'Could you elaborate on that point?', trExample: 'Bu noktayı biraz açar mısınız?' },
    { word: 'intricate', type: 'sıfat', tr: 'karmaşık, girift', en: 'The watch has an intricate mechanism.', trExample: 'Saatin girift bir mekanizması var.' },
    { word: 'mitigate', type: 'fiil', tr: 'etkisini azaltmak', en: 'Planting trees can mitigate the effects of heat.', trExample: 'Ağaç dikmek sıcağın etkilerini azaltabilir.' },
    { word: 'paradoxically', type: 'zarf', tr: 'çelişkili biçimde', en: 'Paradoxically, having more choices can make us less happy.', trExample: 'Çelişkili biçimde, daha fazla seçenek bizi daha az mutlu edebilir.' },
    { word: 'pinpoint', type: 'fiil', tr: 'tam olarak belirlemek', en: 'It is hard to pinpoint exactly when the problem began.', trExample: 'Sorunun tam olarak ne zaman başladığını belirlemek zor.' },
    { word: 'prerequisite', type: 'isim', tr: 'ön koşul', en: 'Basic maths is a prerequisite for this course.', trExample: 'Temel matematik bu kursun ön koşuludur.' },
    { word: 'stem from', type: 'ifade', tr: 'kaynaklanmak', en: 'Many errors stem from carelessness.', trExample: 'Birçok hata dikkatsizlikten kaynaklanır.' },
    { word: 'strive', type: 'fiil', tr: 'çabalamak', en: 'We strive to offer the best service possible.', trExample: 'Mümkün olan en iyi hizmeti sunmaya çabalıyoruz.', tip: 'strive to do / strive for something.' },
    { word: 'viable', type: 'sıfat', tr: 'yaşayabilir, geçerli', en: 'Solar power is now a viable alternative.', trExample: 'Güneş enerjisi artık geçerli bir alternatif.' },
  ],
  C2: [
    { word: 'quintessential', type: 'sıfat', tr: 'en tipik, özünü yansıtan', en: 'Simit is the quintessential İstanbul street food.', trExample: 'Simit, İstanbul sokak lezzetinin en tipik örneğidir.' },
    { word: 'ubiquitous', type: 'sıfat', tr: 'her yerde bulunan', en: 'Smartphones have become ubiquitous in daily life.', trExample: 'Akıllı telefonlar günlük hayatta her yerde bulunur hâle geldi.' },
    { word: 'ephemeral', type: 'sıfat', tr: 'kısa ömürlü, gelip geçici', en: 'Fame on social media is often ephemeral.', trExample: 'Sosyal medyadaki şöhret çoğu zaman gelip geçicidir.' },
    { word: 'juxtapose', type: 'fiil', tr: 'yan yana koymak (karşıtlık için)', en: 'The exhibition juxtaposes ancient and modern art.', trExample: 'Sergi, antik ve modern sanatı yan yana sunuyor.' },
    { word: 'exacerbate', type: 'fiil', tr: 'daha da kötüleştirmek', en: 'Cutting the budget would exacerbate the problem.', trExample: 'Bütçeyi kısmak sorunu daha da kötüleştirir.' },
    { word: 'idiosyncrasy', type: 'isim', tr: 'kişiye özgü tuhaflık', en: 'Every writer has stylistic idiosyncrasies.', trExample: 'Her yazarın üsluba dair kendine özgü tuhaflıkları vardır.' },
    { word: 'obfuscate', type: 'fiil', tr: 'bilerek bulanıklaştırmak', en: 'The report seemed designed to obfuscate rather than clarify.', trExample: 'Rapor, aydınlatmaktan çok bulanıklaştırmak için yazılmış gibiydi.' },
    { word: 'panacea', type: 'isim', tr: 'her derde deva', en: 'Technology is not a panacea for educational problems.', trExample: 'Teknoloji, eğitim sorunlarına her derde deva değildir.' },
    { word: 'pernicious', type: 'sıfat', tr: 'sinsi ve zararlı', en: 'Misinformation has a pernicious effect on public debate.', trExample: 'Yanlış bilgi, kamusal tartışma üzerinde sinsi ve zararlı bir etkiye sahiptir.' },
    { word: 'serendipity', type: 'isim', tr: 'hoş tesadüf', en: 'They met by pure serendipity at a conference.', trExample: 'Bir konferansta tamamen hoş bir tesadüfle tanıştılar.' },
    { word: 'vestige', type: 'isim', tr: 'kalıntı, iz', en: 'The custom is a vestige of an older tradition.', trExample: 'Bu âdet, daha eski bir geleneğin kalıntısıdır.' },
    { word: 'zeitgeist', type: 'isim', tr: 'çağın ruhu', en: 'The film perfectly captures the zeitgeist of the nineties.', trExample: 'Film, doksanların ruhunu kusursuzca yakalıyor.' },
    { word: 'belie', type: 'fiil', tr: 'yalanlamak, gizlemek', en: 'His calm face belied his anxiety.', trExample: 'Sakin yüzü, içindeki kaygıyı gizliyordu.' },
    { word: 'capricious', type: 'sıfat', tr: 'kaprisli, değişken', en: 'Mountain weather is notoriously capricious.', trExample: 'Dağ havası değişkenliğiyle ünlüdür.' },
    { word: 'conflate', type: 'fiil', tr: 'birbirine karıştırmak', en: 'Critics often conflate popularity with quality.', trExample: 'Eleştirmenler popülerlik ile kaliteyi sık sık birbirine karıştırır.' },
    { word: 'disparate', type: 'sıfat', tr: 'birbirinden çok farklı', en: 'The project brings together disparate fields of research.', trExample: 'Proje, birbirinden çok farklı araştırma alanlarını bir araya getiriyor.' },
    { word: 'equivocal', type: 'sıfat', tr: 'kaçamak, iki anlamlı', en: 'The minister gave an equivocal answer to the question.', trExample: 'Bakan soruya kaçamak bir yanıt verdi.' },
    { word: 'gregarious', type: 'sıfat', tr: 'sosyal, girişken', en: 'She has a gregarious personality and loves crowds.', trExample: 'Girişken bir kişiliği var ve kalabalıkları seviyor.' },
    { word: 'incontrovertible', type: 'sıfat', tr: 'tartışılmaz', en: 'The DNA evidence was incontrovertible.', trExample: 'DNA kanıtı tartışılmazdı.' },
    { word: 'intransigent', type: 'sıfat', tr: 'uzlaşmaz', en: 'Negotiations failed because both sides were intransigent.', trExample: 'Müzakereler iki taraf da uzlaşmaz olduğu için başarısız oldu.' },
    { word: 'laconic', type: 'sıfat', tr: 'az ve öz konuşan', en: 'His laconic reply ended the conversation.', trExample: 'Az ve öz yanıtı sohbeti bitirdi.' },
    { word: 'magnanimous', type: 'sıfat', tr: 'alicenap, yüce gönüllü', en: 'She was magnanimous in victory and praised her rival.', trExample: 'Zaferde yüce gönüllüydü ve rakibini övdü.' },
    { word: 'obviate', type: 'fiil', tr: 'gereksiz kılmak', en: 'The new system obviates the need for paper forms.', trExample: 'Yeni sistem kâğıt formlara olan ihtiyacı ortadan kaldırıyor.' },
    { word: 'ostensibly', type: 'zarf', tr: 'görünürde, sözde', en: 'He called, ostensibly to ask about homework.', trExample: 'Görünürde ödevi sormak için aradı.' },
    { word: 'precipitate', type: 'fiil', tr: 'tetiklemek, hızlandırmak', en: 'The scandal precipitated the minister’s resignation.', trExample: 'Skandal, bakanın istifasını hızlandırdı.' },
    { word: 'recalcitrant', type: 'sıfat', tr: 'inatla itaatsiz', en: 'The recalcitrant student refused every suggestion.', trExample: 'İnatla itaatsiz öğrenci her öneriyi reddetti.' },
    { word: 'sycophant', type: 'isim', tr: 'dalkavuk', en: 'Leaders surrounded by sycophants rarely hear the truth.', trExample: 'Etrafı dalkavuklarla çevrili liderler gerçeği nadiren duyar.' },
    { word: 'tantamount to', type: 'ifade', tr: 'eşdeğer, denk', en: 'Ignoring the warning is tantamount to accepting the risk.', trExample: 'Uyarıyı görmezden gelmek, riski kabul etmekle eşdeğerdir.' },
    { word: 'vicissitude', type: 'isim', tr: 'iniş çıkış, değişkenlik', en: 'He stayed calm through all the vicissitudes of life.', trExample: 'Hayatın tüm iniş çıkışlarında sakin kaldı.' },
    { word: 'wry', type: 'sıfat', tr: 'buruk, alaycı', en: 'She greeted the bad news with a wry smile.', trExample: 'Kötü haberi buruk bir gülümsemeyle karşıladı.' },
  ],
};
